language: php

services:
  - docker

before_install:
  - chmod +x entrypoint.sh

jobs:
  include:
    - stage: "Prepare"
      name: "Subindo containers"
      script:
        - docker-compose -f docker-compose.travis.yaml up -d
        - docker ps
        - docker exec -t app cp .env.example .env
        - docker exec -t app ./entrypoint.sh

    - stage: "Tests"
      script: docker exec -t app phpunit -c ./phpunit.xml
