language: php

services:
  - docker

jobs:
  include:
    - stage: "Build"
      script:
        - docker-compose -f docker-compose.travis.yaml up -d
        - docker ps
        - docker exec -t app cp .env.example .env
        - ls
        - chmod +x ./laravel/entrypoint.sh
        - docker exec -t app ./entrypoint.sh

    - stage: "Tests"
      script: docker exec -t app phpunit -c ./phpunit.xml
